version: "3.8"
services:
  llama1b:
    image: ghcr.io/kth8/llama-server:llama-3.2-1b-instruct
    container_name: llama1b
    init: true
    labels:
      - "io.containers.autoupdate=registry"
    ports:
      - "8001:8080/tcp"

  qwen15b:
    image: ghcr.io/kth8/llama-server:qwen2.5-1.5b-instruct
    container_name: qwen15b
    init: true
    labels:
      - "io.containers.autoupdate=registry"
    ports:
      - "8002:8080/tcp"

  smollm17b:
    image: ghcr.io/kth8/llama-server:smollm2-1.7b-instruct
    container_name: smollm17b
    init: true
    labels:
      - "io.containers.autoupdate=registry"
    ports:
      - "8003:8080/tcp"

  amd1b:
    image: ghcr.io/kth8/llama-server:amd-olmo-1b-sft-dpo
    container_name: amd1b
    init: true
    labels:
      - "io.containers.autoupdate=registry"
    ports:
      - "8004:8080/tcp"
