name: Publish Image to GHCR

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.txt"
  schedule:
    - cron: '0 0 * * 0'  # Run at 00:00 UTC on Sunday

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model: [
          Llama-3.2-1B-Instruct,
          Llama-3.2-3B-Instruct
        ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Convert Model Name to Lowercase
        id: lowercase_model
        run: echo "model=$(echo ${{ matrix.model }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Image with Buildah
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          image: llama-server
          tags: |
            ${{ env.model }}
          build-args: |
            MODEL=${{ matrix.model }}

      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
