name: Publish Image to GHCR

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.txt"
  schedule:
    - cron: '0 0 * * 0'  # Run at 00:00 UTC on Sunday

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model: [
          Llama-3.2-1B-Instruct,
          Llama-3.2-3B-Instruct,
          Qwen2.5-0.5B-Instruct,
          Qwen2.5-1.5B-Instruct,
          Qwen2.5-3B-Instruct
        ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Image with Buildah
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          image: ghcr.io/${{ github.repository_owner }}/docker-llama-server:${{ matrix.model }}-${{ github.sha }}
          build_args: |
            MODEL=${{ matrix.model }}

      - name: Convert Model Name to Lowercase
        id: lowercase_model
        run: echo "model=$(echo ${{ matrix.model }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Push Image to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ghcr.io/${{ github.repository_owner }}/docker-llama-server:${{ matrix.model }}-${{ github.sha }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.model }}:${{ github.sha }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
