name: Publish Image to GHCR
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.txt"
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model:
          [
            Llama-3.2-1B-Instruct,
            Llama-3.2-3B-Instruct,
            Qwen2.5-0.5B-Instruct,
            Qwen2.5-1.5B-Instruct,
            Qwen2.5-3B-Instruct,
            Qwen2.5-Math-1.5B-Instruct,
            Qwen2.5-Coder-1.5B-Instruct,
            Yi-Coder-1.5B,
            Yi-Coder-1.5B-Chat,
            gemma-2-2b-it,
            Phi-3.5-mini-instruct,
            Nemotron-Mini-4B-Instruct,
            OLMoE-1B-7B-0924-Instruct
          ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
          
      - name: Convert model name to lowercase
        id: change_case
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ matrix.model }}

      - name: Build Image with Buildah
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: ./Containerfile
          image: llama-server
          archs: amd64, arm64
          tags: ${{ steps.change_case.outputs.lowercase }}
          build-args: MODEL=${{ matrix.model }}
          labels: |
            org.opencontainers.image.description=https://huggingface.co/bartowski/${{ matrix.model }}-GGUF
            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/${{ github.repository }}/main/README.md

      - name: Push Image to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
